# SPDX-FileCopyrightText: Copyright (c) 2024-2026 Yegor Bugayenko
# SPDX-License-Identifier: MIT
---
AllCops:
  Exclude:
    - 'bin/**/*'
    - 'assets/**/*'
    - 'vendor/**/*'
    - 'test/commands/test_print.rb'
    - 'test/commands/test_push.rb'
    - 'test/commands/test_update.rb'
  DisplayCopNames: true
  TargetRubyVersion: 3.2
  SuggestExtensions: false
  NewCops: enable
plugins:
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rake
  - rubocop-elegant
Minitest/EmptyLineBeforeAssertionMethods:
  Enabled: false
Style/GlobalVars:
  Enabled: false
Gemspec/RequiredRubyVersion:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Layout/MultilineMethodCallIndentation:
  Enabled: false
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Layout/CaseIndentation:
  Enabled: false
Naming/MethodParameterName:
  MinNameLength: 2
Layout/EndOfLine:
  EnforcedStyle: lf
Layout/MultilineAssignmentLayout:
  Enabled: true
Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent
Elegant/NoRedundantVariable:
  Exclude:
    - 'lib/judges/commands/test.rb'
    - 'test/commands/test_pull.rb'
Lint/NumberConversion:
  Enabled: false
Performance/ChainArrayAllocation:
  Enabled: false
Elegant/GoodMethodName:
  AllowedNames:
    - method_missing
    - respond_to_missing?
    - each_with_index
    - import_to
    - loop_them
    - one_judge
    - sha384
    - save_it
    - '+'
    - build_options
    - run_judge_in_cycle
    - run_judge_tests
    - skip_test?
    - run_single_test
    - run_after_assertions
    - print_test_summary
    - reorder_judges
    - discover_judges
    - normalize_to_h
    - parse_pairs
Elegant/GoodVariableName:
  AllowedNames:
    - '@to_h'
Elegant/ClassInModule:
  Exclude:
    - 'lib/**/*'
    - '**/test_*.rb'
    - '**/*Test.rb'
Metrics/MethodLength:
  Max: 30
Metrics/AbcSize:
  Max: 55
Metrics/ClassLength:
  Max: 220
Metrics/BlockLength:
  Max: 35
Metrics/CyclomaticComplexity:
  Max: 15
Metrics/PerceivedComplexity:
  Max: 17
Metrics/ParameterLists:
  Max: 5
