# SPDX-FileCopyrightText: Copyright (c) 2024-2025 Yegor Bugayenko
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: eslint
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  eslint:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - run: npm install
      - run: npx eslint .
